import type { Metadata } from "next";
import "./globals.css";
import ReduxProvider from "@/providers/ReduxProvider";
import Settings from "@/components/Settings";

export const metadata: Metadata = {
  title: "ساعتين جد",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar">
      <ReduxProvider>
        <body dir="rtl">
          <Settings />
          {children}
        </body>
      </ReduxProvider>
    </html>
  );
}
